/**
 * Data-source contract tests.
 *
 * These guard the two data files generated by `data-sources` wave:
 *  - src/lib/data/named-colors.ts
 *  - src/lib/data/popular-hexes.ts
 *
 * If these fail after a generator re-run, the structural invariants we depend
 * on for routing, pre-render, and SEO have drifted. Fix the generator before
 * touching the data.
 */
import { describe, it, expect } from 'vitest';
import {
  NAMED_COLORS,
  findByHex,
  findBySlug,
  byFamily,
  type ColorFamily,
} from '../src/lib/data/named-colors';
import { POPULAR_HEXES } from '../src/lib/data/popular-hexes';

const CANONICAL_HEX = /^#[0-9a-f]{6}$/;

describe('NAMED_COLORS', () => {
  it('has unique slugs across every entry', () => {
    const seen = new Set<string>();
    const duplicates: string[] = [];
    for (const entry of NAMED_COLORS) {
      if (seen.has(entry.slug)) duplicates.push(entry.slug);
      seen.add(entry.slug);
    }
    expect(duplicates).toEqual([]);
  });

  it('has canonical lowercase #rrggbb hex for every entry', () => {
    const bad = NAMED_COLORS.filter((c) => !CANONICAL_HEX.test(c.hex));
    expect(bad).toEqual([]);
  });

  it('has unique hex values (de-duplicated at the source)', () => {
    const seen = new Set<string>();
    const duplicates: string[] = [];
    for (const entry of NAMED_COLORS) {
      if (seen.has(entry.hex)) duplicates.push(`${entry.slug}=${entry.hex}`);
      seen.add(entry.hex);
    }
    expect(duplicates).toEqual([]);
  });

  it('uses only valid ColorFamily values', () => {
    const allowed: ColorFamily[] = [
      'red', 'orange', 'yellow', 'green', 'teal', 'blue',
      'indigo', 'purple', 'pink', 'brown', 'gray', 'neutral',
    ];
    const allowedSet = new Set(allowed);
    const bad = NAMED_COLORS.filter((c) => !allowedSet.has(c.family));
    expect(bad).toEqual([]);
  });

  it('uses only valid source values', () => {
    const allowed = new Set(['css', 'tailwind', 'material', 'bootstrap', 'curated']);
    const bad = NAMED_COLORS.filter((c) => !allowed.has(c.source));
    expect(bad).toEqual([]);
  });

  it('has exactly three related slugs per entry, all resolvable', () => {
    const slugSet = new Set(NAMED_COLORS.map((c) => c.slug));
    for (const entry of NAMED_COLORS) {
      expect(entry.related, `entry ${entry.slug}`).toHaveLength(3);
      // The related slug must not be the entry itself.
      for (const sib of entry.related) {
        expect(sib, `entry ${entry.slug} -> ${sib}`).not.toBe(entry.slug);
        expect(slugSet.has(sib), `unresolved related slug ${sib} on ${entry.slug}`).toBe(true);
      }
    }
  });

  it('has a non-empty blurb of 80 or more words for every entry', () => {
    const short: Array<{ slug: string; words: number }> = [];
    for (const entry of NAMED_COLORS) {
      const words = entry.blurb.split(/\s+/).filter(Boolean).length;
      if (words < 80) short.push({ slug: entry.slug, words });
    }
    expect(short, 'blurbs below 80 words').toEqual([]);
  });

  it('caps every blurb at 120 words (upper end of the spec window)', () => {
    const long: Array<{ slug: string; words: number }> = [];
    for (const entry of NAMED_COLORS) {
      const words = entry.blurb.split(/\s+/).filter(Boolean).length;
      if (words > 120) long.push({ slug: entry.slug, words });
    }
    expect(long, 'blurbs above 120 words').toEqual([]);
  });

  it('has zero needsReview flags after the Wave 3b hand-edit pass', () => {
    // The 50 originally-flagged entries were hand-edited in Wave 3b
    // (seo-content). The `needsReview` field is kept on the type for future
    // review queues but the generator no longer emits it by default.
    const flagged = NAMED_COLORS.filter((c) => c.needsReview === true);
    expect(flagged).toHaveLength(0);
  });

  it('has at least one entry per ColorFamily that we serve crawl-graph links from', () => {
    const families: ColorFamily[] = [
      'red', 'orange', 'yellow', 'green', 'teal', 'blue',
      'indigo', 'purple', 'pink', 'brown', 'gray', 'neutral',
    ];
    for (const fam of families) {
      const matched = byFamily(fam);
      expect(matched.length, `family ${fam}`).toBeGreaterThan(0);
    }
  });

  it('exposes findByHex on representative canonical entries', () => {
    expect(findByHex('#ff0000')?.slug).toBe('red');
    expect(findByHex('#0000ff')?.slug).toBe('blue');
    expect(findByHex('#ff7f50')?.slug).toBe('coral');
    expect(findByHex('#000000')?.slug).toBe('black');
    expect(findByHex('#ffffff')?.slug).toBe('white');
    expect(findByHex('#abcdef')).toBeUndefined();
  });

  it('findByHex is case-insensitive on the input', () => {
    expect(findByHex('#FF0000')?.slug).toBe('red');
    expect(findByHex('#FfFfFf')?.slug).toBe('white');
  });

  it('exposes findBySlug on representative entries', () => {
    expect(findBySlug('coral')?.hex).toBe('#ff7f50');
    expect(findBySlug('tailwind-blue-500')?.source).toBe('tailwind');
    expect(findBySlug('bootstrap-primary')?.source).toBe('bootstrap');
    expect(findBySlug('material-red-500')?.source).toBe('material');
    expect(findBySlug('this-slug-does-not-exist')).toBeUndefined();
  });

  it('byFamily returns non-empty arrays for the headline families', () => {
    expect(byFamily('red').length).toBeGreaterThanOrEqual(3);
    expect(byFamily('blue').length).toBeGreaterThanOrEqual(3);
    expect(byFamily('green').length).toBeGreaterThanOrEqual(3);
    expect(byFamily('gray').length).toBeGreaterThanOrEqual(3);
  });

  it('records aliases for canonical synonym entries', () => {
    // CSS named-color synonyms get folded into the canonical entry's aliases.
    expect(findBySlug('cyan')?.aliases).toContain('aqua');
    expect(findBySlug('magenta')?.aliases).toContain('fuchsia');
    expect(findBySlug('gray')?.aliases).toContain('grey');
  });
});

describe('POPULAR_HEXES', () => {
  it('contains at least 2000 entries', () => {
    expect(POPULAR_HEXES.length).toBeGreaterThanOrEqual(2000);
  });

  it('has only canonical lowercase #rrggbb values', () => {
    const bad = POPULAR_HEXES.filter((h) => !CANONICAL_HEX.test(h));
    expect(bad).toEqual([]);
  });

  it('has no duplicates', () => {
    const seen = new Set<string>();
    const duplicates: string[] = [];
    for (const h of POPULAR_HEXES) {
      if (seen.has(h)) duplicates.push(h);
      seen.add(h);
    }
    expect(duplicates).toEqual([]);
  });

  it('is sorted alphabetically for deterministic builds', () => {
    const copy = [...POPULAR_HEXES];
    copy.sort();
    expect(POPULAR_HEXES).toEqual(copy);
  });

  it('contains the iconic round-number hexes', () => {
    // sanity check: black/white and the channel-saturated primaries are
    // mandatory entries.
    for (const must of ['#000000', '#ffffff', '#ff0000', '#00ff00', '#0000ff']) {
      expect(POPULAR_HEXES, `must contain ${must}`).toContain(must);
    }
  });

  it('contains every NAMED_COLORS hex', () => {
    // Every page that has a named entry must also be in the popular-hex
    // pre-render set so it gets a generated /[hex] page in addition to
    // /colors/[name].
    const popularSet = new Set(POPULAR_HEXES);
    const missing = NAMED_COLORS.map((c) => c.hex).filter((h) => !popularSet.has(h));
    expect(missing).toEqual([]);
  });
});
